### ISSUE TITLE
Console keeps displaying this message

### ISSUE THREAD

**Issue by Chaekars** [Archy-X/AuraSkills#248] opened 2024-03-26 03:01 UTC
### Server software and version

1.20.4

### Expected behavior

The error doe not appear

### Actual behavior

- [Tue 02:16:07 ERROR Minecraft] Could not pass event EntityDamageEvent to AuraSkills v2.0.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:277)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1114)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1096)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:926)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148)
    at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2080)
    at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1398)
    at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:301)
    at net.minecraft.world.entity.Entity.ao(Entity.java:610)
    at net.minecraft.world.entity.EntityLiving.ao(EntityLiving.java:405)
    at net.minecraft.world.entity.EntityInsentient.ao(EntityInsentient.java:349)
    at net.minecraft.world.entity.Entity.l(Entity.java:564)
    at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:2840)
    at net.minecraft.world.entity.EntityInsentient.l(EntityInsentient.java:422)
    at net.minecraft.world.entity.monster.EntityZombie.l(EntityZombie.java:234)
    at net.minecraft.server.level.WorldServer.a(WorldServer.java:865)
    at net.minecraft.world.level.World.a(World.java:682)
    at net.minecraft.server.level.WorldServer.lambda$12(WorldServer.java:443)
    at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54)

### How to reproduce

This pops up a couple a second

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment] 2024-03-26 05:17
There should be more lines to the error underneath at the first instance of it happening, saying Caused by... I need that part of the error to investigate.

**Comment by Chaekars** [comment] 2024-03-26 12:27
[12:24:07] [Server thread/ERROR]: Could not pass event EntityDeathEvent to AuraSkills v2.0.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:880) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.EntityLiving.g(EntityLiving.java:1720) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1658) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1484) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.animal.EntitySquid.a(SourceFile:183) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.GlowSquid.a(SourceFile:83) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.animal.EntityWaterAnimal.b(SourceFile:55) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.animal.EntityWaterAnimal.ao(SourceFile:66) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.Entity.l(Entity.java:564) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:2840) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.EntityInsentient.l(EntityInsentient.java:422) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:865) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.level.World.a(World.java:682) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.level.WorldServer.lambda$12(WorldServer.java:443) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:423) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1301) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.persistence.PersistentDataContainer.has(org.bukkit.NamespacedKey)'
	at dev.aurelium.auraskills.bukkit.source.EntityLeveler.getBleedDamager(EntityLeveler.java:237) ~[?:?]
	at dev.aurelium.auraskills.bukkit.source.EntityLeveler.onEntityDeath(EntityLeveler.java:55) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor330.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 25 more

**Comment by Chaekars** [comment] 2024-03-26 12:28
it stops me there in the logs

**Comment by Archy-X** [comment] 2024-03-26 17:33
This is fixed in the latest dev buil: https://aurelium.dev/auraskills/download?channel=dev

**Closed by Archy-X** 2024-03-26 17:33 UTC
Labels: type: bug
