### ISSUE TITLE
fishing rod's "grappler" skill can ignore residence's permission

### ISSUE THREAD

**Issue by minecraft-dripdrop** [Archy-X/AuraSkills#264] opened 2024-04-20 14:28 UTC
### Server software and version

purpur 1.20.1

### Expected behavior

The armor_stand in other player's residence can't be moved by fishing rod

### Actual behavior

with this plugin,players can use fishing rod to pull out the armorstand outside the residence and then steal equipments.

### How to reproduce

1.install RESIDENCE plugin
2.create a residence using command /res create test
3. put a armorstand in the residence
4. other player (no permission),can use fishing_rod to move the armorstand

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment] 2024-05-01 02:38
Can you check if the issue is fixed in the latest dev build? https://aurelium.dev/auraskills/download?channel=dev

**Closed** 2024-06-04 07:48 UTC
Labels: type: bug
