### ISSUE TITLE
Terraform + AdvancedEnchantments can cause the server to crash 

### ISSUE THREAD

**Issue by Nanpure** [Archy-X/AuraSkills#250] opened 2024-03-26 17:41 UTC
### Server software and version

Paper 1.20.4

### Expected behavior

Terraform should activate as expected.

This crash does not happen with Aurellium Skills 1.3.24.

### Actual behavior

Server crashes.

### How to reproduce

/advancedenchantments admin

Give self book on Trench

AdvancedEnchantments/enchantments.yml:
```trench:
  display: '%group-color%Trench'
  description: Break in 3x3 area.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: FABLED
  settings:
    not-applyable-with:
    - hasten
    - haste
    - veinminer
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      effects:
      - BREAK_BLOCK @Trench{r=3}
```

Apply to shovel.

/sk skill setlevel nanpure excavation 10

Right click with shovel to activate Terraform, then try to dig. The server crashes.

### Additional information

```10:47:06 [Server thread/ERROR] Could not pass event BlockBreakEvent to AuraSkills v2.0.3
java.lang.StackOverflowError: null
        at java.lang.ClassLoader.defineClass0(Native Method) ~[?:?]
        at java.lang.System$2.defineClass(System.java:2390) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2505) ~[?:?]
        at java.lang.invoke.InvokerBytecodeGenerator.loadMethod(InvokerBytecodeGenerator.java:249) ~[?:?]
        at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:712) ~[?:?]
        at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:849) ~[?:?]
        at java.lang.invoke.LambdaForm.prepare(LambdaForm.java:807) ~[?:?]
        at java.lang.invoke.MethodHandle.<init>(MethodHandle.java:482) ~[?:?]
        at java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:52) ~[?:?]
        at java.lang.invoke.BoundMethodHandle$Species_L.<init>(BoundMethodHandle.java:210) ~[?:?]
        at java.lang.invoke.BoundMethodHandle$Species_L.make(BoundMethodHandle.java:225) ~[?:?]
        at java.lang.invoke.BoundMethodHandle.bindSingle(BoundMethodHandle.java:66) ~[?:?]
        at java.lang.invoke.SimpleMethodHandle.copyWithExtendL(SimpleMethodHandle.java:71) ~[?:?]
        at java.lang.invoke.MethodHandles.argumentsWithCombiner(MethodHandles.java:6266) ~[?:?]
        at java.lang.invoke.MethodHandles.filterArgumentsWithCombiner(MethodHandles.java:6223) ~[?:?]
        at java.lang.invoke.StringConcatFactory.prepender(StringConcatFactory.java:777) ~[?:?]
        at java.lang.invoke.StringConcatFactory.prepender(StringConcatFactory.java:789) ~[?:?]
        at java.lang.invoke.StringConcatFactory.filterInPrependers(StringConcatFactory.java:621) ~[?:?]
        at java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:549) ~[?:?]
        at java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:365) ~[?:?]
        at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:102) ~[?:?]
        at java.lang.invoke.CallSite.makeSite(CallSite.java:316) ~[?:?]
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274) ~[?:?]
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264) ~[?:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:69) ~[paper-1.20.4.jar:git-Paper-454]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.breakBlock(Terraform.java:112) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.terraformBreak(Terraform.java:97) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.applyTerraform(Terraform.java:78) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.onBreak(Terraform.java:64) ~[AuraSkills-2.0.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor749.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-454]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-454]
        ...
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakBlock(DropsHandler.java:621) ~[AdvancedEnchantments-9.7.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:521) ~[AdvancedEnchantments-9.7.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.7.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.7.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor347.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-454]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-454]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.breakBlock(Terraform.java:112) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.terraformBreak(Terraform.java:97) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.applyTerraform(Terraform.java:78) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.onBreak(Terraform.java:64) ~[AuraSkills-2.0.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor749.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-454]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-454]
        ...
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakBlock(DropsHandler.java:621) ~[AdvancedEnchantments-9.7.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:521) ~[AdvancedEnchantments-9.7.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.7.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.7.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor347.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-454]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-454]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.breakBlock(Terraform.java:112) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.terraformBreak(Terraform.java:97) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.applyTerraform(Terraform.java:78) ~[AuraSkills-2.0.3.jar:?]
        at dev.aurelium.auraskills.bukkit.skills.excavation.Terraform.onBreak(Terraform.java:64) ~[AuraSkills-2.0.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor749.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-454]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-454]
        ...
```

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by matipoirierg** [comment] 2024-04-06 18:42
Same issue!

**Comment by GC-spigot** [comment] 2024-04-06 18:44
Looks like got caused by an update of AuraSkills. We've already spent 20+ hours adding support for AureliumSkills and every problem that comes with it, working on hackarounds just the most random problems. Seems like this is on AuraSkills.

**Comment by Archy-X** [comment] 2024-04-06 19:00
> Looks like got caused by an update of AuraSkills. We've already spent 20+ hours adding support for AureliumSkills and every problem that comes with it, working on hackarounds just the most random problems. Seems like this is on AuraSkills.

AuraSkills needs to be able to detect if a BlockBreakEvent is caused by AE or the other way around. A simple way to fix this without even needing to use the AuraSkills API is to either mark blocks broken by AE with the metadata block-ignore or call a custom class that extends BlockBreakEvent instead of BlockBreakEvent itself when breaking extra blocks. You can see how AuraSkills handles those here: https://github.com/Archy-X/AuraSkills/blob/master/bukkit/src/main/java/dev/aurelium/auraskills/bukkit/skills/excavation/Terraform.java#L60

Also, can you please verify me on your Discord (archyx.)? I've been trying to get into contact with you guys for a bit.

**Comment by Archy-X** [comment] 2024-04-07 18:14
@Nanpure @matipoirierg Can you see if it's fixed in the latest dev build? https://aurelium.dev/auraskills/download?channel=dev

**Comment by zhro** [comment] 2024-04-10 23:16
@Archy-X I tested version 2.0.6 and this does solve the crash problem. However, the behavior not what would be expected. Shovels which have the "Trench" enchantment excavate every time a block is broken. Aura Skill's Terraform ability is activated. The expected behavior is for Trench to take priority until Terraform is activated, then Terraform should activate exclusively instead.

**Comment by matipoirierg** [comment] 2024-04-11 01:45
> @Archy-X I tested version 2.0.6 and this does solve the crash problem. However, the behavior not what would be expected. Shovels which have the "Trench" enchantment excavate every time a block is broken. The expected behavior is for Trench to stop when Terraform is activated, because Terraform is more powerful, hence why it is a mana ability on a cooldown.
> 
> If we were to allow Trench of shovels again, players would have to carry around _two_ shovels, one for use with Trench and another to swap to as the non-Trench shovel just to use Terraform. This is undesirable.

can confirm this

**Comment by Archy-X** [comment] 2024-04-11 01:49
In that case something would probably have to be done on the AdvancedEnchantments side to detect Terraform. They are in the process of remaking the hook for AuraSkills so I can bring this up to them.

**Comment by zhro** [comment] 2024-04-11 02:18
AdvancedEnchantments has a mechanism to test conditions before activating an effect. These conditions are fully customizable from the config file. PlaceholderAPI works within conditions, so exposing whether an ability is active through Aura Enchantments can allow an effect conditionally, without having either side to provide a workaround, except in the case of crashes.

```
conditions:
- '%player auraskills_ability_terraform% = 1 : %allow%'
```

https://wiki.advancedplugins.net/abilities/conditions/conditions-variables


> ### PlaceholderAPI support
> E.g: %victim player_level% > 10 : %stop%, player_level is a PlaceholderAPI placeholder %player_level%. 
> 
> You can use %player %, %attacker % or%victim %
> 
> It's a must to remove percentage signs from PlaceholderAPI placeholders, more examples: %server_online% -> server_online -> %player server_online% > 5 : %allow%

**Closed** 2024-04-20 02:41 UTC
Labels: type: bug
